name: CD Pipeline


on:
  push:
    tags:
      - "**" # matches every branch

permissions:
  id-token: write
  checks: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Wait for CI to succeed
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: 'Run Test'
          repo-token: ${{ secrets.TOKEN_SECRET }}
          wait-interval: 10

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::340752803932:role/github-action
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: sample-repo
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      # - uses: yumafuu/docker-build-ecr-push-action@v1
      #   with:
      #     aws_role_arn: arn:aws:iam::340752803932:role/github-action
      #     aws_region: eu-central-1
      #     ecr_repo: sample-repo
      #     tag: v1
