name: CD Pipeline


# on:
#   push:
#     branches:
#       - "**" # matches every branch
on:
  workflow_run:
    workflows: ["CI pipeline"]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Wait for CI to succeed
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: 'checkout'
          repo-token: ${{ secrets.TOKEN_SECRET }}
          wait-interval: 10

      - name: checkout repository
        uses: actions/checkout@v2
      
      - name: setting up python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"
      
      # - name: install dependencies
      #   run: pip install -r requirements.txt

      # - name: Running isort checks
      #   run: isort --check-only  .

      # - name: Running flake8 checks
      #   run: flake8 .
      
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ vars.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
        
      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest